---
channels:
  - "defaults"
  - "conda-forge"
  - "beakerx"

dependencies:
  - scipy
  - jupyterlab >=2.0,<3.0
  - matplotlib
  - pandas >= 1.3
  - seaborn
  - statsmodels
  # beakerx extensions
  - beakerx_kernel_autotranslation
  - beakerx_tabledisplay
  - beakerx_widgets
  - pip
  - pip:
    - ipykernel
    - import-ipynb
